### ISSUE TITLE
server side generated templates, similar to `erb`, using Tera

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#26]
It can't hurt adding a proper html/text view generation facility into `views`.
right now we're doing JSON but its almost free to add server generated HTML, for those who want to build both an API and a mini website.

Each view should embed the template file,
Some provisions could be made to compile-time include the Tera templates, and then just generate them with a given information struct.

**Comment by silicakes** [comment]
Can we go with some adapter strategy to help people incorporate their own things? 
We can use Tera as an example, but eventually grow into other things as well.

**Comment by jondot** [comment]
Hi 👋
could you maybe sketch out in code how do you see it working? (im assuming some dynamic templating adapter, like Express has)

**Comment by silicakes** [comment]
👋 
I'm relatively new to rust so it's gonna be a bit hard, but let's try and sketch out a general design:
Express implements it in two ways:
1. The native template library, pug, for instance, implements an internal `_express(...` function that's being invoked by express when the template engine is set.

2. There's an adapter called [consolidate.js](https://github.com/tj/consolidate.js) that adapts various templates into express.

We will probably go with #2 for now so if we'll take Tera's example:

```rs
use tera::Context;
// Using the tera Context struct
let mut context = Context::new();
context.insert("product", &product);
context.insert("vat_rate", &0.20);
tera.render("products/product.html", &context)?;

#[derive(Serialize)]
struct Product {
    name: String
}
// or a struct
tera.render("products/product.html", &Context::from_serialize(&product)?)?;
```

We can create some kind of configuration in the sense of `app.set_templating_engine("Tera", {...tera_options})` which will point to `tera.render` which we can call with an agnostic `template!("template_name.html", context)`

We can do the same for handlebars and liquid as long as we can maintain a reasonable DX for developers.

This leads me to another point, which is **a case against Tera**.

since they use `*.html` files by default, it will break the IDE's parsing/syntax highlighting since they'll try to infer the template as proper HTML which isn't fun.

I think that the first templating language we'll use should have the following:

1. Treesitter support (or any other parser, with popular IDE's)
2. LSP support for intellisense


[liquid](https://github.com/cobalt-org/liquid-rust) is one example that comes to mind.
It comes with [support for treesitter ](https://github.com/Shopify/tree-sitter-liquid?search=1)and its LSP support is being [actively developed](https://github.com/panoply/liquify)

Having it using the `*.liquid` file extension also helps IDEs to distinguish it from other languages and avoid mixups.
The rust version follows the original Ruby one which was developed by Shopify and is actively maintained by it.

WDYT?

**Comment by jondot** [comment]
Thanks, look like a good starting point.
Some more for you to consider:

* In general, we want a user to deploy a *single binary* and a configuration file. This means all templates need to get embedded as part of the binary. We already use Tera and rendering in the mailer infrastructure: [example mailer embedding a complete folder](https://github.com/loco-rs/loco/blob/master/examples/demo/src/mailers/auth.rs#L9) and the [infrastructure to render](https://github.com/loco-rs/loco/blob/master/src/mailer/template.rs). This obsoletes a lot of Tera's "dynamic nature" of loading templates from disk, caching the templates, etc, which *can be a disadvantage*, BUT -- the trade off for us is developer happiness, so deployment is super simple.
* You can name Tera templates anything you like (we choose an arbitrary `.t`, but I think `.tera` might have syntax highlighters)
* `liquid` is a native library, Tera is implemented in Rust, so our tendency is not to use native libraries where a pure Rust alternative exists, especially if the alternative is feature-comparable
* `consolidate` was great. I believe that the key is *simplicity* and little moving parts. If you can create the same abstraction, and it is very simple (small API surface, easy to configure) then we should go for it. I think the best way to discover is to create an experimental branch and start building something like consolidate. As you build it, see what walls you hit and come back for discussion

**Comment by isaacdonaldson** [comment]
Are there plans to introduce support for flash and sessions with a default templating implementation?

**Comment by kaplanelad** [comment]
@isaacdonaldson, not at the moment. We're currently trying to avoid of creating a starter per specific usecase

If you think that your suggestion could or should be incorporated into the library, feel free to open an issue, and we can discuss it there. Your input is more than welcome!

**Comment by jakswa** [comment]
> ❯ Stateless HTML (minimal, no db)

I don't see this in the starter options, and I'm in here on the hunt for the easy/quick server-side-templating path

**Comment by nalaka** [comment]
@kaplanelad - Stateless HTML (minimal, no db) is no longer an option in `loco new`

```shell
➜  tmp git:(main) loco new
✔ ❯ App name? · stateless_html
? ❯ What would you like to build? ›
❯ lightweight-service (minimal, only controllers and views)
  Rest API (with DB and user auth)
  Saas app (with DB and user auth)
```

I was looking for an example of using a template for rendering HTML.

Thanks.
