### ISSUE TITLE
Create a CLI commands that shows all routes

### ISSUE THREAD

**Issue by kaplanelad** [loco-rs/loco#27]
We can adding a cli commands which prints all the application routes.
for example 
```sh
rr controllers

[Methos] [URI]
```

**Comment by jondot** [comment]
Also try 
```
lc routes --curl
```

to output a simplistic curl command for each of the routes (when POST, use a small json object `-d {"data":"hello"}` or similar.

note:
* alias will change to `alias lc='cargo run --'` (because `loco` bin is the new project generator)
* Rails uses `rails routes` and not `rails controllers` so let's follow that too

**Comment by kaplanelad** [comment]
First pr show all register controller: https://github.com/loco-rs/loco/pull/35
