### ISSUE TITLE
Add an integrated template rendering stack + i18n

### ISSUE THREAD

**Issue by alexhumphreys** [loco-rs/loco#329]
## Feature Request

I couldn't find anything in the repo/roadmap in terms of internationalization (i18n). As i18n is usually easier to have from the start rather then to add later, it would be cool if there was some form of loco support for i18n out of the box. 

**Describe the solution you'd like**

No strong preference on "the solution I'd like". The usual basic solution for this is abstracting out the strings the application produces, and looking up the values in different languages. Same for things like date/currency formats that change between regions. Can check out the [Rails Internationalization (I18n) API](https://guides.rubyonrails.org/i18n.html) to see how they solve it.

**Describe alternatives you've considered**

Looks like loco is using [`tera`](https://docs.rs/tera/latest/tera/) for templating. There's this [`fluent-templates`](https://github.com/XAMPPRocky/fluent-templates#tera) crate which provides integration between the [fluent localization framework](https://projectfluent.org/) and tera. Maybe that or something similar could work?

PS. thanks for all the work on Loco, it's pretty sweet and just the kind of thing I've been looking for as I get into Rust ❤️

**Comment by jondot** [comment]
Thanks Alex!

Do you see the i18n infra available through Tera? meaning this is the place where you need i18n support?

**Comment by alexhumphreys** [comment]
Suppose it could be needed anywhere there's a string that can be shown to an end user in a different region. The two places I can think of like that are in templates, and error message strings, but I'm maybe missing some other places.

Guess it comes up a bit more in server rendered HTML apps, rather than apps just exposing pure json APIs, so guess it depends on exactly what usecases you have in mind for loco

**Comment by jondot** [comment]
To make it a bit more actionable I guess we can start with integrating fluent-templates into our Tera support. Would you want to create a PR for it?

**Comment by alexhumphreys** [comment]
Hmm before I open try get something in a PR, any idea what you'd like the interface to this to be? 

It looks like the three parts involved in using fluent-templates are:
- [import the locale directory](https://github.com/XAMPPRocky/fluent-templates/blob/master/README.md?plain=1#L184)
- [register a `fluent` function with tera, and pass the locale info as an argument](https://github.com/XAMPPRocky/fluent-templates/blob/master/README.md?plain=1#L197)
- [call the render function, while using the `fluent` function in your template](https://github.com/XAMPPRocky/fluent-templates/blob/master/README.md?plain=1#L200)

I've got my own [little axum app](https://github.com/alexhumphreys/rust-template) where I tried implementing fluent-templates though I went wit handlebars rather than tera for templating). I didn't want to have to do those 3 steps each time I handled a request, so instead I did the first 2 at startup and put the result in the [app state here](https://github.com/alexhumphreys/rust-template/blob/4172adc717205d0d42bd593b1545427cadfe1143/website/src/app_state.rs#L22) (which is I think the equivalent of your [`AppContext` here](https://github.com/loco-rs/loco/blob/78489a501b7038bbf571ceb226e8a9bd2da2d9c8/src/app.rs#L31)?). I could then call it from request handlers [as seen here](https://github.com/alexhumphreys/rust-template/blob/4172adc717205d0d42bd593b1545427cadfe1143/website/src/handlers.rs#L34).

I'm pretty new to rust/axum, so I'm not sure if that's a good approach, or something that'd work for loco. Also not sure how this would tie into the current [`src/tera.rs`](https://github.com/loco-rs/loco/blob/master/src/tera.rs) and [`src/mailer/template.rs`](https://github.com/loco-rs/loco/blob/master/src/mailer/template.rs). Maybe you can give your opinion on all this as an approach?

**Comment by jondot** [comment]
Thanks for the thoughtful analysis! indeed this has just become a design challenge.

To look at this we have:

* Some user state which is costly to initialize (a locale db/cache)
* A need to "wire" in the functionality into our templating library
* Passing the state into every template that's being rendered

Let me ponder about the design a bit and post some more information once I get something smart to say

**Comment by jondot** [comment]
I think your direction is correct.
Though, a variant of that is saying something like:

* Initialize your "tera stack" (we have plenty of places for that kind of initialization in Loco, we can get to specifics later)
* Provide it through a Tera extractor (meaning, it stays off the central `AppContext`, and state is preserved through its own layer)
* To use it, in your routes you use the extractor: `fn do_something(Tera(tera):Tera) -> ...`

This helps make Tera a "pay as you go". If you use it, great, but if you don't -- you pay nothing for it. In addition, we can say -- you want to use Handlebars? fine -- you can create something very similar in structure and operation and use it in the same way.

### A note about "all in one" engines

A generic template engine I found: https://github.com/Altair-Bueno/axum-template/tree/main which is similar to how it works on Rails or Express. An important note, I think, that in Rust we better be explicit and not generic about templating, because there's a price to pay by using each engine -- and in Rust thinking -- a user should always be aware of the price they pay. So if a user wants to use Handlebars and they know it's slower and bulkier, it should be right infront of them. Which is why I would prefer providing 2 different extractors for Tera and / or Handlebars instead of integrating a magic engine that dynamically switches between renders.

Note that I'm 80% confident on that conclusion, not completely, and would like to be persuaded otherwise.

### Summary

I think providing a first-class Tera extractor, with its own layer, and then initialization code for templates, locales, i18n, etc actually forms our "a-la Rails ActionView" render stack.

I'd be happy to look at a draft PR for this if you'd like to work on it, and then we can shape it together into a part of the framework in a form of `Initializer` (this is a new concept addition to Loco since v0.2.0) which people can opt-in and take.

**Comment by jondot** [comment]
Yes, and also as a shortcut, you can check the `llm-inference` example here: https://github.com/loco-rs/loco/blob/master/examples/llm-candle-inference/src/app.rs#L44 where we use an `Extension` layer just to experiment.
The best thing is for it to have its own layer.

**Comment by alexhumphreys** [comment]
Ah, so you can just use the `Extension` to pass in state, then [extract that state later](https://github.com/loco-rs/loco/blob/master/examples/llm-candle-inference/src/controllers/home.rs#L13) in the controllers? Nice!

Might take me a while to have a nice tidy version that's tested, but I've started hacking on this over [here](https://github.com/alexhumphreys/loco/commit/3f89b6088b5e54690aa999f3900291c739b765c5). Won't have much time to work on this over the next few, but will open up a draft PR when I have something reasonable, and can iterate from there.

**Comment by nalaka** [comment]
@jondot - Hi, is there an example of using Tera (or something else) for templating when returning HTML?

Below works - but looking for a way to have the HTML template in a file like we already have for mailers.

```rust
const GET_LOGIN_TEMPLATE: &str = "<div>HTML for the login form here</div>";

pub async fn get_login(State(_ctx): State<AppContext>) -> Result<Html<String>> {
    html(GET_LOGIN_TEMPLATE)
}
```
Looks like [the "Stateless HTML" starter used to do this](https://github.com/loco-rs/loco/issues/26#issuecomment-1844959677) but it is now available with `loco new` any more - @kaplanelad

Thanks to the two of you for putting out Loco - loving it so far. 💯

**Comment by nalaka** [comment]
@jondot - Hi, is there an example of using Tera (or something else) for templating when returning HTML?

Below works - but looking for a way to have the HTML template in a file like we already have for mailers.

```rust
const GET_LOGIN_TEMPLATE: &str = "<div>HTML for the login form here</div>";

pub async fn get_login(State(_ctx): State<AppContext>) -> Result<Html<String>> {
    html(GET_LOGIN_TEMPLATE)
}
```
Looks like [the "Stateless HTML" starter used to do this](https://github.com/loco-rs/loco/issues/26#issuecomment-1844959677) but it is not available with `loco new` any more - @kaplanelad

Thanks to the two of you for putting out Loco - loving it so far. 💯

**Comment by kaplanelad** [comment]
@nalaka we replaced the name of stateless html to `Saas app`

**Comment by slyons** [comment]
Is there any chance we can feature-gate this? Not every site is going to need template rendering
