### ISSUE TITLE
loco rs support htmx 

### ISSUE THREAD

**Issue by ghost** [loco-rs/loco#483]
loco rs support htmx ???

**Comment by schungx** [comment]
Yes it does.  As a matter of fact, I'm developing an entire LOB app with HTMX and Loco, trying to do without a single line of JavaScript.  So far so good.

But of course, since HTMX works with HTML instead of JSON, the examples are not gonna help you.  Your main public workhorse will be a bunch of HTML API's.

Technically you don't need all those JSON API's (unless you need them for other purposes).  However, I find that it is best to expose them anyway, because you're gonna need them anyway -- Loco uses Tera as a templating engine, which accepts JSON inputs.  Therefore, you'll find that you're calling your JSON API in your HTML request handler, then rendering HTML for return.
