### ISSUE TITLE
loco-cli should warn when trying to create an app inside another git repository

### ISSUE THREAD

**Issue by assapir** [loco-rs/loco#487]
## Feature Request

Every developer did it at least once in their life - starting a new project (`npm init`/`loco new`) inside an already existing project, then realizing it too late and starting moving things.

**Describe the solution you'd like**

I would like the loco-cli to warn the user when running the command if there is a `.git` folder up in the directory tree and ask them explicitly to allow that.

**Describe alternatives you've considered**

1st alternative: As of today, ignore that, which I obviously don't think it's a good idea.
2nd alternative: Don't allow that at all. I think this alternative is too strict to the other side when sometimes the user does want to do that.
  - This can be done by allowing an explicit flag to the command line, but because it's already interactive, why not keep it interactive?

As a side note, I would love to help develop this feature request with appropriate mentoring.

**Comment by jondot** [comment]
We'll be happy to mentor you through this one!

Just to start out, here's some additional context in text. As you move forward, we can add in an offline/async fashion here, just chat around questions, or if needed go in a Zoom as well.

-------

Echoing your idea -- since loco generates within a new folder, let's take an ambiguous name which can be anything: "apps":

OK: (in this case `apps` is a general folder where i keep _all of my apps_)

```
~apps/
     myapp/ <---- newly generated directory
```

BAD: (in this case `apps` is a repo)
```
~apps/
     .git/   <---- we're using this to indicate 'projects' is a directory where it is a project in and of itself.
      myapp/ <---- new directory
```

Intended behavior in the second case is some kind of "are you sure that blah blah blah?"

1. You can add a command for checking if we're in a repo (better to defer this to Git itself, and not try to detect by sniffing out folders up a tree), somewhat like this: https://github.com/loco-rs/loco/blob/master/loco-cli/src/git.rs#L137
2. Note that we typically shell out to `git` and not use `libgit` because of compatibility reasons, this is the safest most compatible route
3. Review the flow here: https://github.com/loco-rs/loco/blob/master/loco-cli/src/bin/main.rs#L49 to add your additional check
4. In general, add a bypass / override from ENV, so that we can run unattended in tests / CI to test this feature

**Comment by assapir** [comment]
implemented in https://github.com/loco-rs/loco/pull/489, will be happy for a review
