### ISSUE TITLE
Generate scaffold not create relationship id in controler

### ISSUE THREAD

**Issue by enieber** [loco-rs/loco#515]
**Description**

When I create scaffold with relationship the model has created with all validation, but the controller not create params with relationship, so when I create request to controller send id of relationship the reply of api is status code 400. Investigating the generated code I find the problem is not create relationship in params of controller receive json.

**To Reproduce**

- create project 
- create role scaffold: `cargo loco generate scaffold role code:string `
- run migration: `cargo loco db migrate`
- create classification scaffold: `cargo loco generate scaffold classification name:string`
- run migration: `cargo loco db migrate`
- create item scaffold with role reference and classification:  `cargo loco generate scaffold item code:string role:references  classification:references `
- run migration: `cargo loco db migrate`
- so the project result in this code: https://github.com/enieber/gen_relationship

**Expected Behavior**

The generate scaffold with references add id of references [like this](https://github.com/enieber/gen_relationship/commit/951fc8945f4f8d5d8dc535d31547c4c3c6851622)

**Comment by jondot** [comment]
Thanks for your feedback and opening an issue! It's a good way to show the problem.
Please note that this behavior is by design. See [scaffold.rs](https://github.com/loco-rs/loco/blob/master/src/gen/scaffold.rs#L70), the reference columns are intentionally not included in Params generation.

This is to avoid parameter overriding or mass-assignment attacks. See [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Mass_Assignment_Cheat_Sheet.html)

I'm happy that you use advanced concepts like relationships! please keep using it. For handling reference columns assignment it's best to always use your own judgement and manual code it without accepting it from the end user.
