### ISSUE TITLE
Make it easier to change JWT algorithm

### ISSUE THREAD

**Issue by alexhumphreys** [loco-rs/loco#583]
**Description**

Right now loco allows you to change the algorithm for JWT tokens [here](https://github.com/loco-rs/loco/blob/e5d6f1a01927d9a8fba2080b3302bf68f60181e0/src/auth/jwt.rs#L47).

However, when [generating tokens](https://github.com/loco-rs/loco/blob/e5d6f1a01927d9a8fba2080b3302bf68f60181e0/src/auth/jwt.rs#L74), loco uses the [`from_base64_secret`](https://docs.rs/jsonwebtoken/latest/jsonwebtoken/struct.EncodingKey.html#method.from_base64_secret) function, which [only supports](https://github.com/Keats/jsonwebtoken/blob/afbb44e34dbd721c35dedb68ec13a86ff6db6d8b/src/encoding.rs#L29) HMAC algorithm [family](https://github.com/Keats/jsonwebtoken/blob/master/src/algorithms.rs#L70).

**Suggestion**

I'd say if you're allowing to change the algorithm, either document that only HMAC algorithms are supported, or maybe enforce it with some sort of type/runtime check.

Alternatively, make the `EncodingKey::from_base64_secret` configurable so it's possible to use a different algorithm and [one of the other functions](https://docs.rs/jsonwebtoken/latest/jsonwebtoken/struct.EncodingKey.html) to get the secret

**Comment by alexhumphreys** [comment]
Don't know the relative strength of the algorithms, I'm not an expert. But I think HMAC algorithm is symmetrical, so JWT tokens are signed and validated with the same key. Whereas the Rsa family use public private keys, so they can be created on one server with the private key, and validated on a different server with the public key that can be shared around.
Assuming I'm not misunderstanding something, then I guess this is more about use-cases then about algorithm strength.

**Comment by jondot** [comment]
Getting back after spending some time on this, I think we can summarize as follows:

* When the server issuing the JWT is the one verifying it (e.g. normal login scenarios -- a user is given a token as proof for their authentication which is later verified), symmetrical algorithms are critical. Trust is central, and so the issuer must be the verifier (think about conditions such as _invalidation_, where the issuer renders a token invalid). And so this is why the current JWT algorithm must be exclusively used for login purposes.
* When we're in a multi-server / federated authentication (e.g. an "authentication server"), then the issuer only plays a game of handing out a ticket saying "this request _may be_ valid", and in this scenario we definitely don't want multiple servers sharing a shared key. I'm also saying _may be valid_ and not _absolutely valid_ because just as with your SSL certificates on your browsers, pub/priv key may have expiry, or alternatively may have been dimmed invalid, but the distributed nature of other servers -- is that they will keep believing a request is valid even if it is signed by -- what now is dimmed invalid -- key.

So now, what i'm most interested in is, figuring out how to strongly emphasize this difference, and having 80% of the users (which only want a "normal" login) not wander around into pub/priv crypto which holds some tricky workflows for them to digest.

Technically we only need to enable the `pem` feature in `jsonwebtoken` and then dig a hole in the configuration for taking different configuration flags, add a couple of lines of code in `jwt.rs` and we're done. 

I'd be happy to accept a PR that would strongly push for HMAC and have a secondary / side-stepped feature of "if you want priv/pub you should know what you're doing, but that's possible too"
