### ISSUE TITLE
Use git tags for released versions of loco

### ISSUE THREAD

**Issue by alexhumphreys** [loco-rs/loco#584]
**Description**

Right now it's not clear which version of the source code is used to build the released versions. From searching around, I _think_ 0.4.0 is built from the [`prep-0.4.0` branch
](https://github.com/loco-rs/loco/tree/prep-0.4.0), but I'm not sure.

**Expected Behavior**

It would be cool if the repo used [git tags](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) to tag the commits that released versions are built from. Ran into this issue when trying to update the examples of a project based on loco, and didn't notice that [the demo example in loco](https://github.com/loco-rs/loco/tree/master/examples/demo) is based on the master branch, and as such has [the unreleased breaking change around `query::dsl`](https://github.com/loco-rs/loco/pull/566). 

Checking the [`.github/workflows`](https://github.com/loco-rs/loco/tree/master/.github/workflows) dir I couldn't see any automation around releases. If there is some that I haven't noticed let me know, I could try make this change.

**Comment by jondot** [comment]
Thanks, indeed I think we missed that. 
To release we use our local testing automation: https://github.com/loco-rs/loco/blob/master/xtask/src/bump_version.rs 
It bumps the version, rewrites versions on the starters and tests all combinations of starters, examples, etc.
Then we would push the crates.

Usually we:


1. Bump
2. Process stops because of failures breakage etc, we fix
3. Bump again and complete the process

So, I believe once completed successfully in (3) we can also create a local git tag

**Comment by kaplanelad** [comment]
Thanks, @alexhumphreys, for the feedback. 
We started adding the git tag version. 

https://github.com/loco-rs/loco/tags
