### ISSUE TITLE
OpenApi spec generation

### ISSUE THREAD

**Issue by askasp** [loco-rs/loco#612]
Hi! I cant find any way to generate an openapi spec for my CRUD api. Before i've used Utopia, but to introduce it here i would need to override your generators. Is this something you're working on?

**Comment by jondot** [comment]
I looked at openapi/swagger when we first created the model abstractions. 
The good news is that we created a "gap" between our controllers and axum, so that things like this can be inserted.
The bad news is that openapi/swagger is still something that people argue about, there isn't a single format that makes describing APIs as a full thing (API, examples, docs), so we decided to not decide.
If you have a realistic idea how this might work, or examples in other rust based projects, we can take a look

**Comment by jondot** [comment]
Closing due to duplication (see linked issues above)
