### ISSUE TITLE
starter: a minimal rest-api starter without views, auth and (mailers)

### ISSUE THREAD

**Issue by haoxins** [loco-rs/loco#676]
## Feature Request 

The most important scenario for me is building internal service within the enterprising VPC network.
So the most suitable starter for me is the `rest-api` starter but without `views`, `auth`, and `mailers`.
And this is a wide scenario for a lot of users.
Can we add a streamlined version of `rest-api` starter?

**Comment by kaplanelad** [comment]
Hey @haoxins
I believe that `views` are quite relevant in this context. The purpose of views is to create an intermediary layer that manages the JSON schema responses from your API. For example, instead of directly returning the entire user model, you can use a view to control which fields and their corresponding names are included in the API response. This approach allows for better management and flexibility of the data exposed by your API.

Authentication is optional and not mandatory. If you don't want your endpoint to be under the auth middleware, you can simply exclude the middleware in the controller.

The same applies to mailers.

We are not planning to create different starters for specific use cases, as there are many. When you create the selected template, you can remove or change anything to fit your use case.

**Comment by haoxins** [comment]
> I believe that views are quite relevant in this context.

oh, thanks, I think I misunderstood the `views` role in the loco.
