### ISSUE TITLE
Is it a reasonable idea to add a request directory to place the request parameter format? Just like the views directory

### ISSUE THREAD

**Issue by HelloReboot** [loco-rs/loco#734]
<img width="164" alt="image" src="https://github.com/user-attachments/assets/73e28e7c-79bd-4e22-8c0c-906716b0ec09">

**Comment by HelloReboot** [comment]
so should I implement the validator of query params  in model ? this is a little confused.

**Comment by kaplanelad** [comment]
Hey @HelloReboot,

Validation is typically designed for models, not query parameters. 
However, if you want to validate request parameters, you can implement a separate validation layer in the controller using the same crate.

**Comment by jondot** [comment]
I think you're describing input data validation. I would put this either in the `controllers/` folder because it's a controllers concern, or in a `controllers/params/` subfolder for example. 

The idea is that without controllers, these data structures have no meaning, and so -- they should somehow be located in proximity with your controllers concept.

**Comment by HelloReboot** [comment]
@kaplanelad   yes. bro. you are correct , I am newbie  still learning how to do it.. however thank you for your reply.

**Comment by HelloReboot** [comment]
@jondot   thank you for explain that.  do you have any example for loco please?

**Comment by jondot** [comment]
sure, see here: https://github.com/loco-rs/loco/blob/master/examples/demo/src/controllers/notes.rs#L16

closing for now
