### ISSUE TITLE
RFC: The road to OpenAPI specs

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#778]
Hi all,

**This is a "request for comments" issue. Please feel free to add comments, pointers, ideas under this thread.**

I'd like to use this issue to define a goal:

> Zero friction API spec generation from an existing app to unlock API client generation.

This includes: (1) describing APIs (2) describing data objects

Developer experience goals:

* Ultimately "magically" understand what needs to be spec'd from current code
* Otherwise, provide as minimal repetition as possible
* Be a non mandatory thing. No changes to code code or ways of working, be able to use and avoid using this feature when you like.
* As specs some time are synonyms for "verbose, redundant" be as minimally verbose as possible. Give people assists: via our codegen? via other mechanism? (macros, other kind of magic)
* Investment should lead to more than 1:1 value. E.g if I choose to invest in specifying my API I want to gain 10x the investment: generate API clients, automate testing or generate tests, provide Rails-like "route magic" where you can say `new_movies_path` and get the specific path under the hood.  

------

Leading options:

* [utoipa](https://github.com/juhaku/utoipa/tree/master/utoipa-axum) - custom router, macros, annotate and then build a router from annotations. has redundant repetition of information. **some redundant information but can be separated**.
* [aide](https://github.com/tamasfe/aide/blob/master/examples/example-axum/src/todos/routes.rs) - requires using custom api router + manual extra annotations. has redundant repetition of information.

Alternatives:

* https://github.com/jakobhellermann/axum_openapi
* https://github.com/kurtbuilds/oasgen 

Related issues:

* https://github.com/loco-rs/loco/issues/640
* https://github.com/loco-rs/loco/issues/632

**Comment by aurelien-clu** [comment]
Disclaimer I have not really used any of them so what follows are surface thoughts and no judgements to any of the work done. 😉 

That being said, **I prefer [utoipa](https://github.com/juhaku/utoipa) over others.**

## [utoipa](https://github.com/juhaku/utoipa) vs [aide](https://github.com/tamasfe/aide)

- activity (latest commit on main: 6 months ago vs 6 hours)
- documentation ([utoipa](https://github.com/juhaku/utoipa) `README` is well made - documentation on `doc.rs` both looks good)
- community: 2,200⭐ & 97 contributors vs 400⭐ & 27 contributors => we can expect more support and updates in the future on [utoipa](https://github.com/juhaku/utoipa)
- usage: it is a matter of taste, I prefer the way of [utoipa](https://github.com/juhaku/utoipa) of macro that looks like documentation rather than having another functions but both have their own merits

[github.com/juhaku/utoipa/examples/todo-axum/src/main.rs](https://github.com/juhaku/utoipa/blob/master/examples/todo-axum/src/main.rs)

```rust
#[utoipa::path(
    post,
    path = "",
    request_body = Todo,
    responses(
        (status = 201, description = "Todo item created successfully", body = Todo),
        (status = 409, description = "Todo already exists", body = TodoError)
    )
)]
async fn create_todo(...) [...]
```

[github.com/tamasfe/aide/examples/example-axum/src/todos/routes.rs](https://github.com/tamasfe/aide/blob/master/examples/example-axum/src/todos/routes.rs)

```rust
async fn create_todo(...) [...]

fn create_todo_docs(op: TransformOperation) -> TransformOperation {
    op.description("Create a new incomplete Todo item.")
        .response::<201, Json<TodoCreated>>()
}
```

## [oasgen](https://github.com/kurtbuilds/oasgen)

[oasgen](https://github.com/kurtbuilds/oasgen) looks nice but I don't know about the feature parity against [utoipa](https://github.com/juhaku/utoipa) and since it has a smaller community (100⭐) it looks like a risky choice unless `loco` team and contributors would be willing to support and contribute to it if needed though I feel like it would be best to keep your manpower on `loco`.

## [axum_openapi](https://github.com/jakobhellermann/axum_openapi)

Latest commit was 3 years ago so I would not consider it as an option unless the work is taken by the `loco` team but I believe such magical and ideal implementation should probably be taken by the `axum` team itself and it does not look like they have the time for it.

[github.com/tokio-rs/axum/issues/50](https://github.com/tokio-rs/axum/issues/50)

## Final thoughts

[utoipa](https://github.com/juhaku/utoipa) does the job, will continue to do the job and is a safer choice. The developer experience looks good, it could be better and more magical but I don't think there is such option right now. 

Might as well have a good developer experience and openapi available rather than nothing imho.

`loco` could also go for [utoipa](https://github.com/juhaku/utoipa) and [utoipauto](https://github.com/ProbablyClem/utoipauto) to improve the developer experience further.

**Comment by jondot** [comment]
We're now concluding the research, here's our findings:

* OpenAPI support will be shown _by example_ and not part of core Loco, as libraries and standards are still shifting.
* The search for "holy grail" automatic inference of how Axum describes an API and conversion of this directly into OpenAPI spec - there is no such thing and _redundancy of information_ as of this writing will always exist

To push forward this task, we've implemented an _example_ of how to use `utoipa` with Loco, and we'll close the issue but monitor how this space evolves from time to time. Check it out [here](https://github.com/loco-rs/loco/tree/master/examples/demo#openapi-with-utoipa)

Thanks for everyone contributing insights!
