### ISSUE TITLE
Add hot reload for tera templates

### ISSUE THREAD

**Issue by Swoorup** [loco-rs/loco#920]
## Feature Request

Can we add hot reload mechanism for tera templates.

**Is your feature request related to a problem? Please describe.**

N/a

**Describe the solution you'd like**

Editing tera .html files should result in immediate changes without compiling source. See also https://www.reddit.com/r/rust/comments/1f2rbe7/livereload_using_tera_in_axum

**Describe alternatives you've considered**

N/A

**Comment by jondot** [comment]
Thanks for the feedback!
We actually experimented with this (see [https://github.com/loco-rs/loco/blob/master/src/controller/views/engines.rs#L57](https://github.com/loco-rs/loco/blob/master/src/controller/views/engines.rs#L57))
Then we commented it out because it meant having `unsafe` code in Loco.

We want to bring it back, but only if we can make sure that it's only enabled in Debug builds, and no `unsafe` code in the Loco framework.

Right now we're recommending `cargo-watch` until we can find a good idea to accomplish the above.

**Comment by jondot** [comment]
I've implemented #977 as the simplest way to achieve a reload effect.
let's take your #930 and turn it into a live-reload only integration, if you can shape it in a form of a middleware that would be the best option for us 👍 
closing this one
