### ISSUE TITLE
Support for layered configuration management?

### ISSUE THREAD

**Issue by adevore** [loco-rs/loco#981]
## Feature Request

Web servers often benefit from pulling configuration from multiple sources. For example, most configuration may be included in the main repository, while secrets are in a separate repository and environmental variables are used as overrides. I frequently use Dynaconf for this in Python.

Currently, a limited form of this is possible with the Tera template engine with `get_env` and a default. However, setting it up is tedious. Also, using `get_env` alone only works with environmental variables.

There are two alternatives in the Rust ecosystem, config and figment. I don't have experience with either one, but I'm willing to put some time into researching if this is a possibility. Config has some built-in async support included, but I'm not sure how important that is in practice. Figment has some tricks that look handy for testing. It also has more extensive docs.

**Comment by jondot** [comment]
hi! thanks for this!
we kinda steered away from figment and the like. the reason is that it is hard to reason about where config comes from, which creates a mental friction.
so, we agressively limited how config "layering" works in this way:

* keep 1 file per environment
* via `get_env` pull what ever you want from ENV (you can use what ever tooling you want to inject to env, advanced, or not a-la 12-factor apps)
* use YAML to allow for "yaml includes" for those wanting to optimize their config
* allow for partials (via Tera, again)
* finally, allow for "local-only" config via [environmentname].local.yaml which is overriding for your local environmnet

so *some* kind of flexibility allowed but mostly -- flat is king.

I think to still extract some insights here maybe you can give some concrete examples where you bumped into a wall, i'm genuinely interested to see what we missed
